itea_project/itea_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('auth-urls/', include('client_app.urls', namespace='client_app')),
    path('vue-example/' , include('vue_example.urls' , namespace='vue'))
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itea_project/library/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index , name='home'),
    path('test/', views.test),
    path('about-us-and-my-project/', views.about , name='about'),
    path('best-book/', views.best_book),
    path('sales/', views.sales),
    path('article-by-user/', views.article_by_user , name='article-by-user'),
    path('to-do-list-project/' , views.to_do),
    path('info-book/<int:pk>' , views.info_book , name='info-book'),
    path('search' , views.search , name='search'),
]



calc_urls = [
    path('calc/' , views.calc)
]

urlpatterns += calc_urls



from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itea_project/library/models.py
from django.db import models
from django.utils.timezone import datetime
from PyPDF2 import PdfFileReader
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

import os


class Book(models.Model):
    GENRE = (
        ('programming', 'Программирование'),
        ('fantastic', 'Фантастика'),
        ('drama', 'Драма'),
        ('comedy', 'Комедия'),
    )

    title = models.CharField(max_length=255, verbose_name='Название книги')
    text = models.TextField(max_length=1000, verbose_name='Текст')
    price = models.FloatField(verbose_name='Цена')
    image = models.ImageField(upload_to='image_book', default='', blank=True, null=True)
    create_at = models.DateTimeField(default=datetime.now)
    document = models.FileField(upload_to='documents/', default='', blank=True, null=True)
    genre = models.CharField(max_length=50, choices=GENRE, default='')
    is_sale = models.BooleanField(default=False)
    percent_sale = models.FloatField(validators=[MinValueValidator(0.0),
                                                 MaxValueValidator(100.0)],
                                     default=0.0)

    def __str__(self):
        return self.title

itea_project/library/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from .models import Book

from client_app.models import Article

# Create your views here.


def index(request):
    ctx = {}
    ctx['all_books'] = Book.objects.all().order_by('-create_at')
    ctx.update({'x': 45})
    ctx['current_tab'] = 'main'
    ctx['select'] = Book.GENRE
    return render(request, 'library/main.html', ctx)


def test(request):
    return HttpResponse('test!!!!')


def about(request):
    ctx = {}
    ctx['current_tab'] = 'about'
    return render(request, 'library/about.html', ctx)


def calc(request):
    ctx = {}
    calc_obj = {
        '+': lambda a, b: a + b,
        '-': lambda a, b: a - b,
        '/': lambda a, b: a / b,
        '*': lambda a, b: a * b,
    }
    ctx['current_tab'] = 'calc'
    ctx['operations'] = list(calc_obj.keys())

    if request.method == 'POST':
        try:
            a = int(request.POST.get('first'))
            oper = request.POST.get('oper')
            b = int(request.POST.get('second'))
            res = calc_obj[oper](a, b)
            ctx.update({
                'res': res
            })
        except (ValueError, KeyError) as e:
            ctx['error'] = e

    return render(request, 'calc.html', ctx)


def best_book(request):
    return render(request, 'library/best_book.html', {})


def sales(request):
    return render(request, 'library/sales.html', {})


def article_by_user(request):
    ctx  = {

    }
    ctx['all_articles'] = Article.objects.filter(status='publish')
    return render(request, 'library/article_by_user.html', ctx)


def to_do(request):
    return render(request, 'library/to_do_list.html', {})


from PyPDF2 import PdfFileReader

import sys, os
from itea_project import settings

sys.path.append('/media/')


def info_book(request, pk):
    book = Book.objects.get(pk=pk)
    ctx = {
        'book_instance': book,
        # 'count_page': PdfFileReader(open(os.path.join(book.document.path), "rb")).getNumPages()
    }
    try:
        ctx['count_page'] = PdfFileReader(open(os.path.join(book.document.path), "rb")).getNumPages()
    except Exception as e:
        ctx['error'] = 'Файла нет.'
    return render(request, 'library/book_info.html', ctx)


def search(request):
    ctx = {}
    if request.method == 'GET':
        try:
            q = request.GET.get('query')
            ctx['all_books'] = Book.objects.filter(genre=q)
            ctx['current_tab'] = 'main'
            ctx['select'] = Book.GENRE
            ctx['q'] = [elem[1]  for elem in Book.GENRE if elem[0] == q][0]
        except Exception as e:
            print(e)
            print(filter_arg)
            ctx['all_books'] = Book.objects.filter(**filter_arg)
        return render(request, 'library/main.html', ctx)

itea_project/itea_project/templates/library/about.html
{% extends 'index.html' %}

{% block content %}
    <h1>About page!</h1>
{% endblock %}

itea_project/itea_project/templates/library/article_by_user.html
{% extends 'index.html' %}

{% block content %}
<h1>Article by user page!</h1>
<div class="book-wrapper">
    {% for article in all_articles %}
    {% include 'includes/article_item.html' with object=article %}
    {% endfor %}
</div>

{% if messages %}
{% for  msg in messages %}
<script>

    alert('{{msg}}');
</script>
{% endfor %}
<!--<h1>{{messages}}</h1>-->

{% endif %}
{% endblock %}

itea_project/itea_project/templates/library/best_book.html
{% extends 'index.html' %}

{% block content %}
    <h1>Best book page!</h1>
{% endblock %}

itea_project/itea_project/templates/library/book_info.html
{% extends 'index.html' %}
{% load poll_extras %}

{% block css %}
<style>
    .old-price {
        background: orangered;
        padding: 5px;
    }

    .new-price {
        background: forestgreen;
        padding: 5px;
    }
</style>
{% endblock %}
{% block content %}
<a href="/">на главную</a>
<h1>Вы смотрите книгу "{{book_instance.title}}"
    {% if count_page %}
    - {{count_page}} стр.
    {% endif %}</h1>

{% if book_instance.image %}
<img style="max-width: 50%" src="{{book_instance.image.url}}" alt="{{book_instance.title}}" title="{{book_instance.title}}">
{% else %}
<h1>Без фото</h1>
{% endif %}
<p>{{book_instance.text}}</p>
<hr>
<p>Цена - {{book_instance.price}} грн</p>
<hr>
<p>Добавлена - {{book_instance.create_at}} </p>
<hr>
<p>Жанр - {{book_instance.get_genre_display}}</p>
<hr>

{% if book_instance.is_sale %}
<p class="old-price">
    Старая цена - <span style="text-decoration:line-through">{{ book_instance.price }} грн</span>
</p>
<p class="new-price">
    Новая цена -{{ book_instance.price|new_price:book_instance.percent_sale }} грн
</p>
{% else %}
<p class="list-group-item ">Цена -{{ book_instance.price }} грн</p>
{% endif %}


{% if book_instance.document %}
<p>
    <a href="{{book_instance.document.url}}" target="_blank">Читать ({{count_page}} стр.)</a>
</p>
{% endif %}

{% endblock %}

itea_project/itea_project/templates/library/main.html
{% extends 'index.html' %}

{% block title %}
Главная
{% endblock %}

{% block css %}
<style>



    .book-item.sale:after {
        content: 'Акция';
        display: block;
        position: absolute;
        top: -10px;
        right: 0px;
        background: #ffdf35;
        color: black;
        border-radius: 5px;
        padding: 10px;
    }
</style>
{% endblock %}

{% block content %}
{% if q %}
Все что смогли найти по жанру "{{q}}"
{% endif %}
<!--<p>{{'LSTRGHSGjh hgashdghasgd '|lower}}</p>-->

<h1>Список книг({{all_books|length}})</h1>
<span>Поиск по жанру</span>
<form action="{% url  'search' %}" method="get">
    <select name="query" id="">
        <option value="-1">Все категории</option>
        {% for elem in select %}
        <option value="{{elem.0}}">{{elem.1}}</option>
        {% endfor %}
    </select>
    <button type="submit">Найти</button>
</form>
<br>
<hr>
<div class="book-wrapper">
    {% for book in all_books %}
    <div class="card book-item {% if book.is_sale %} sale {% endif %}" style="width: 18rem;">

         {% if book.image %}
        <img class="card-img-top" src="{{book.image.url}}" alt="Card image cap">
         {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{book.title}}</h5>
            <p class="card-text">{{book.text|truncatechars:'77'}}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">{{book.price}} грн</li>
            <li class="list-group-item">{{book.create_at}}</li>
        </ul>
        <div class="card-body">
            <a href="{% url 'info-book' pk=book.id %}" class="card-link">Card link</a>
        </div>
    </div>
    {% endfor %}
</div>

{{x}}
{% endblock %}

{% block form%}

{% endblock %}

itea_project/itea_project/templates/library/sales.html
{% extends 'index.html' %}

{% block content %}
    <h1>Sales page!</h1>
{% endblock %}

itea_project/itea_project/templates/library/to_do_list.html
{% extends 'index.html' %}

{% block content %}
    <h1>To do list!!!</h1>
    <ol>
        <li>Сделать вывод всех книг</li>
        <li>Сделать книги по акции</li>
        <li>Сделать локализацию </li>
        <li>Сделать отправку писем в телеграмм , почту </li>
        <li>Сделать водный знак</li>
        <li>django rest framework</li>
        <li>динамические ссылки</li>
        <li>slug ссылки</li>
        <li>meta class</li>
        <li>slot class</li>
    </ol>
{% endblock %}
d

git clone https://gitlab.com/antonmazun/test_itea_django.git

python -m venv env

cd env/Scripts
activate

pip install -r req.txt

python manage.py makemigrations
python manage.py migrate

python manage.py createsupeuser