itea_project/client_app/urls.py
from django.urls import path, include, re_path
from . import views , auth_views

app_name = 'client_app'
urlpatterns = [
    path('cabinet', views.cabinet, name='cabinet'),
    path('change_color', views.change_color, name='change_color'),
    path('set-to-wish-list', views.set_to_session, name='set-to-wish-list'),
    path('write_post', views.write_post, name='write_post'),
    path('my_articles', views.my_articles, name='my_articles'),
    path('wish-list/<int:pk>/', views.wish_list, name='wish-list'),
    path('article-item/<int:pk>',
         views.article_item,
         name='article-item'),
    path('add-commen/<int:article_id>' , views.add_comment , name='add_comment'),
    path('filter_by_status/<str:status>' ,
         views.filter_by_status ,
         name='filter_by_status'),
    path('delete_article/<int:pk>' , views.delete_article  , name='delete_article'),
    path('show_article/<int:pk>' , views.show_article  , name='show_article')

]

auth_urls = [
    path('', auth_views.login_, name='login'),
    path('register', auth_views.register_, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.activate, name='activate'),
    path('logout', auth_views.logout_, name='logout'),
]

urlpatterns += auth_urls

itea_project/itea_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('auth-urls/', include('client_app.urls', namespace='client_app')),
    path('vue-example/' , include('vue_example.urls' , namespace='vue'))
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itea_project/library/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index , name='home'),
    path('test/', views.test),
    path('about-us-and-my-project/', views.about , name='about'),
    path('best-book/', views.best_book),
    path('sales/', views.sales),
    path('article-by-user/', views.article_by_user , name='article-by-user'),
    path('to-do-list-project/' , views.to_do),
    path('info-book/<int:pk>' , views.info_book , name='info-book'),
    path('search' , views.search , name='search'),
]



calc_urls = [
    path('calc/' , views.calc)
]

urlpatterns += calc_urls



from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itea_project/vue_example/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'vue'
urlpatterns = [
    path('', views.main_vue, name='main'),
    path('api/', include('vue_example.api_urls'))

]

itea_project/itea_project/templates/includes/article_item.html
<div class="card book-item {% if object.is_sale %} sale {% endif %}" style="width: 18rem;">
    {% if book.image %}
    <img class="card-img-top" src="{{object.image.url}}" alt="Card image cap">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{object.title}}</h5>
        <p class="card-text">{{object.content|safe}}</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">@{{object.author.user}}</li>
        <li class="list-group-item">{{object.create_at}}</li>
    </ul>
    <div class="card-body">
        <a href="{% url 'client_app:article-item' pk=object.id %}" class="card-link">Читать</a>
    </div>
    {% if del == True %}
    <a href="{% url 'client_app:wish-list' pk=object.id %}">Delete</a>
    {% else %}
    <form action="{% url 'client_app:set-to-wish-list' %}" >
        <input type="hidden" name="article_id" value = {{object.id}}>
        <button>Отложить на чтение</button>
    </form>
    {% endif %}
</div>

itea_project/itea_project/templates/includes/footer.html
<footer>
    footer!
</footer>

itea_project/itea_project/templates/includes/header.html
{% load poll_extras %}
{% load i18n %}

<!--<header>-->
    <!--<nav>-->
        <!--<a {% if current_tab == 'main' %} class='active' {% endif %} href="/"></a>-->
        <!--<a {% if current_tab == 'about' %} class='active' {% endif %} href="{% url 'about' %}">О нас</a>-->
        <!--<a href="/best-book/">Лучшие книги</a>-->
        <!--<a href="/sales/">Акции</a>-->
        <!--<a href="{% url 'client_app:cabinet' %}">Мой кабинет</a>-->
        <!--<a href="/article-by-user/">Статьи от пользователей</a>-->
        <!--<a href="/to-do-list-project/">to-do-list-project</a>-->
        <!--<a {% if current_tab == 'calc' %} class='active' {% endif %} href="/calc/">Калькулятор</a>-->

        <!--{% if request.user.is_authenticated %}-->
        <!--<a href="{% url 'client_app:logout' %}">Выход({{request.user.username}})</a>-->
        <!--{% else %}-->
        <!--<a href="{% url 'client_app:login' %}">Войти</a>-->
        <!--<a href="{% url 'client_app:register' %}">Регистрация</a>-->
        <!--{% endif %}-->
    <!--</nav>-->
<!--</header>-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">LESSONS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if current_tab == 'main' %} active {% endif %}">
        <a class="nav-link" href="/">Главная <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if current_tab == 'about' %} active {% endif %}">
        <a class="nav-link" href="{% url 'about' %}">{% trans 'О нас' %}</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/best-book/">Лучшие книги</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/article-by-user/">Статьи от пользователей</a>
      </li>
     <li class="nav-item">
        <a class="nav-link" href="{% url 'vue:main' %}">Example vue</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Остальное
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/to-do-list-project/">to-do-list-project</a>
          <a class="dropdown-item" href="/calc/">Калькулятор</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
    </ul>
    <a href="{% url 'client_app:wish-list' pk=0 %}" class="btn btn-warning">Не забыть почитать ({{request.session.read_article|length}})</a>
      <div class="my-2 my-lg-0">
                  <a class="btn btn-info" href="{% url 'client_app:cabinet' %}">Мой кабинет</a>
            {% if request.user.is_authenticated  %}
         <a class="btn btn-success" href="{% url 'client_app:logout' %}">Выход({{request.user.username}})</a>
           {% else %}
      <a href="{% url 'client_app:login' %}" class="btn btn-success">Вход</a>
          <a href="{% url 'client_app:register' %}" class="btn btn-primary">Регистрация</a>
        {% endif %}
      </div>
  </div>
</nav>